# Generated by Django 2.0.7 on 2018-10-14 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0014_news'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='bde',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bde.bde'),
            preserve_default=False,
        ),
    ]
