# Generated by Django 2.0.7 on 2018-08-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilapp', '0001_initial'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebde',
            name='etudiantc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilapp.etudiant'),
            preserve_default=False,
        ),
    ]
