# Generated by Django 2.0.7 on 2018-08-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_messagebde_etudiantc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebde',
            name='bdec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.bde'),
        ),
    ]
