# Generated by Django 2.0.7 on 2018-09-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0012_auto_20180901_1508'),
        ('messagerie', '0004_auto_20180824_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageanon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=2000)),
                ('bdec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.bde')),
            ],
        ),
    ]
