# Generated by Django 2.0.7 on 2018-08-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bde', '0010_auto_20180820_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='TresoOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateop', models.DateField(auto_now_add=True)),
                ('titre', models.CharField(max_length=50)),
                ('bdeconcerne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bde.bde')),
            ],
        ),
    ]
