# Generated by Django 2.0.7 on 2018-08-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdeapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tresoop',
            name='bdeconcerne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.bde'),
        ),
    ]
