# Generated by Django 2.0.7 on 2018-09-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0012_auto_20180901_1508'),
        ('utilapp', '0008_auto_20180824_1730'),
        ('bdeapps', '0002_auto_20180823_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=300)),
                ('places', models.IntegerField()),
                ('date', models.DateTimeField(blank=True)),
                ('lieu', models.CharField(max_length=50)),
                ('prive', models.BooleanField(default=False)),
                ('typeevent', models.CharField(max_length=30)),
                ('invites', models.ManyToManyField(to='utilapp.etudiant')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.bde')),
            ],
        ),
        migrations.CreateModel(
            name='Usermail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
