# Generated by Django 2.0.7 on 2018-09-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdeapps', '0003_event_usermail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='typeevent',
            new_name='type_evenement',
        ),
        migrations.AddField(
            model_name='usermail',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bdeapps.event'),
            preserve_default=False,
        ),
    ]
