# Generated by Django 2.0.7 on 2018-09-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdeapps', '0004_auto_20180902_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
