# Generated by Django 2.0.7 on 2018-09-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0012_auto_20180901_1508'),
        ('utilapp', '0008_auto_20180824_1730'),
        ('bdeapps', '0005_auto_20180902_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=25)),
                ('Description', models.TextField(max_length=300)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('par_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilapp.etudiant')),
                ('pour_bde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bde.bde')),
            ],
        ),
    ]
