# Generated by Django 2.0.7 on 2018-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdeapps', '0006_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invites',
            field=models.ManyToManyField(blank=True, to='utilapp.etudiant'),
        ),
    ]
