# Generated by Django 2.0.7 on 2018-09-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilapp', '0008_auto_20180824_1730'),
        ('bdeapps', '0007_auto_20180909_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='par_utilisateur',
        ),
        migrations.AddField(
            model_name='mission',
            name='par_utilisateur',
            field=models.ManyToManyField(blank=True, to='utilapp.etudiant'),
        ),
    ]
