# Generated by Django 2.0.7 on 2018-10-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdeapps', '0010_auto_20180911_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsasso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
    ]
