# Generated by Django 2.0.7 on 2018-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='demande_bde',
            field=models.ManyToManyField(related_name='demande_bde', to='bde.bde'),
        ),
    ]
