# Generated by Django 2.0.7 on 2018-08-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0002_etudiant_demande_bde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='BDE',
            new_name='bdechoisi',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='demande_bde',
            field=models.ManyToManyField(blank=True, null=True, related_name='demande', to='bde.bde'),
        ),
    ]
