# Generated by Django 2.0.7 on 2018-08-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0003_auto_20180801_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='demande_bde',
            field=models.ManyToManyField(blank=True, related_name='demande', to='bde.bde'),
        ),
    ]
