# Generated by Django 2.0.7 on 2018-08-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0004_auto_20180802_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('localisation', models.CharField(max_length=30)),
                ('bdeappartenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bde.bde')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='etablissement',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='imagesetudiant'),
        ),
    ]
