# Generated by Django 2.0.7 on 2018-08-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('bde', '0006_auto_20180816_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='bdechoisi',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='demande_bde',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='etudiant',
        ),
    ]
