# Generated by Django 2.0.7 on 2018-08-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0007_auto_20180817_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='bde',
            name='image',
            field=models.ImageField(default='media/defaultbde.png', upload_to='bde_images'),
        ),
    ]
