# Generated by Django 2.0.7 on 2018-08-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0010_auto_20180820_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bdeappartenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bde.bde'),
        ),
    ]
