# Generated by Django 2.0.7 on 2018-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0012_auto_20180901_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bde',
            name='adresse',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bde',
            name='etablissement',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bde',
            name='image',
            field=models.ImageField(default='media/defaultbde.png', null=True, upload_to='bde_images'),
        ),
    ]
