# Generated by Django 2.0.7 on 2018-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0013_auto_20180926_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=300)),
                ('image', models.ImageField(default='media/defaultbde.png', null=True, upload_to='news_images')),
                ('T1', models.CharField(max_length=50)),
                ('D2', models.TextField(max_length=300)),
            ],
        ),
    ]
