# Generated by Django 2.0.7 on 2018-08-17 14:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('bde', '0007_auto_20180817_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(default='media/default.png', upload_to='imagesetudiant')),
                ('etablissement', models.CharField(max_length=30)),
                ('bdechoisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bde.bde')),
                ('demande_bde', models.ManyToManyField(blank=True, related_name='demande', to='bde.bde')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
