# Generated by Django 2.0.7 on 2018-08-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilapp', '0002_etudiant_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='poste',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Tresorier', 'Tresorier'), ('Membre', 'Membre')], max_length=15, null=True),
        ),
    ]
