# Generated by Django 2.0.7 on 2018-08-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilapp', '0003_auto_20180823_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membrebde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiantlie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilapp.etudiant')),
            ],
        ),
    ]
