# Generated by Django 2.0.7 on 2018-08-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bde', '0010_auto_20180820_1428'),
        ('utilapp', '0006_auto_20180824_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrebde',
            name='bdechoisi',
        ),
        migrations.RemoveField(
            model_name='membrebde',
            name='etudiantlie',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='bdechoisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bde.bde'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='poste',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Tresorier', 'Tresorier'), ('Membre', 'Membre')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Membrebde',
        ),
    ]
