# Generated by Django 2.0.7 on 2018-08-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilapp', '0007_auto_20180824_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissionsbde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_perm', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='permissions_bde',
            field=models.ManyToManyField(blank=True, to='utilapp.Permissionsbde'),
        ),
    ]
