# Generated by Django 2.0.7 on 2018-09-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilapp', '0008_auto_20180824_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='demandenom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilapp.etudiant')),
            ],
        ),
    ]
